"""
Core monitoring engine for the Water Quality Sentinel.

The WaterQualityMonitor ingests sensor readings, evaluates them against
configured thresholds, generates alerts when thresholds are violated, and
dispatches those alerts to registered handlers.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import List, Optional

from .handlers import AlertHandler, LoggingAlertHandler
from .models import Alert, AlertSeverity, SensorReading, WaterParameter
from .storage import AlertStore, ReadingStore
from .thresholds import ThresholdConfig, DEFAULT_THRESHOLDS

logger = logging.getLogger(__name__)


class WaterQualityMonitor:
    """Processes sensor readings and generates alerts for threshold violations.

    Example usage::

        from water_quality_sentinel import WaterQualityMonitor, SensorReading, WaterParameter

        monitor = WaterQualityMonitor()
        reading = SensorReading(
            parameter=WaterParameter.PH,
            value=9.5,
            unit="pH",
            sensor_id="sensor-001",
            location="Intake A",
        )
        alerts = monitor.process(reading)

    Args:
        thresholds: Threshold configuration to use. Defaults to
            ``DEFAULT_THRESHOLDS``.
        reading_store: Storage backend for sensor readings. A new in-memory
            store is created if not provided.
        alert_store: Storage backend for alerts. A new in-memory store is
            created if not provided.
        handlers: Alert notification handlers. Defaults to a single
            ``LoggingAlertHandler``.
    """

    def __init__(
        self,
        thresholds: Optional[ThresholdConfig] = None,
        reading_store: Optional[ReadingStore] = None,
        alert_store: Optional[AlertStore] = None,
        handlers: Optional[List[AlertHandler]] = None,
    ) -> None:
        self.thresholds = thresholds if thresholds is not None else DEFAULT_THRESHOLDS
        self._reading_store = reading_store if reading_store is not None else ReadingStore()
        self._alert_store = alert_store if alert_store is not None else AlertStore()
        self._handlers: List[AlertHandler] = (
            handlers if handlers is not None else [LoggingAlertHandler()]
        )

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def add_handler(self, handler: AlertHandler) -> None:
        """Register an additional alert notification handler."""
        self._handlers.append(handler)

    def process(self, reading: SensorReading) -> List[Alert]:
        """Ingest a sensor reading and return any triggered alerts.

        The reading is always stored.  If a threshold violation is detected,
        an ``Alert`` is created, stored, and dispatched to all registered
        handlers.

        Args:
            reading: The sensor reading to evaluate.

        Returns:
            A (possibly empty) list of alerts generated by this reading.
        """
        self._reading_store.add(reading)
        alerts: List[Alert] = []

        result = self.thresholds.evaluate(reading.parameter, reading.value)
        if result is not None:
            severity, threshold_value = result
            alert = self._build_alert(reading, severity, threshold_value)
            self._alert_store.add(alert)
            self._dispatch(alert)
            alerts.append(alert)

        return alerts

    def get_active_alerts(self) -> List[Alert]:
        """Return all currently active (unacknowledged) alerts."""
        return self._alert_store.get_active()

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert by its ID.

        Returns:
            True if the alert was found and acknowledged, False otherwise.
        """
        return self._alert_store.acknowledge(alert_id)

    def get_latest_reading(self, parameter: WaterParameter) -> Optional[SensorReading]:
        """Return the most recent reading for a parameter."""
        return self._reading_store.get_latest(parameter)

    def get_status_summary(self) -> dict:
        """Return a snapshot of the current status of all monitored parameters.

        Returns a dict mapping parameter names to a dict with keys:
        ``latest_value``, ``unit``, ``status`` (``"ok"``, ``"warning"``,
        or ``"critical"``), and ``timestamp``.
        """
        summary = {}
        for param in WaterParameter:
            reading = self._reading_store.get_latest(param)
            if reading is None:
                summary[param.value] = {"status": "no_data"}
                continue

            result = self.thresholds.evaluate(param, reading.value)
            if result is None:
                status = "ok"
            else:
                status = result[0].value

            summary[param.value] = {
                "latest_value": reading.value,
                "unit": reading.unit,
                "status": status,
                "timestamp": reading.timestamp.isoformat(),
                "sensor_id": reading.sensor_id,
                "location": reading.location,
            }
        return summary

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_alert(
        reading: SensorReading,
        severity: AlertSeverity,
        threshold_value: float,
    ) -> Alert:
        direction = "below" if reading.value < threshold_value else "above"
        message = (
            f"{reading.parameter.value.replace('_', ' ').title()} {direction} "
            f"{severity.value} threshold: {reading.value:.4f} {reading.unit} "
            f"(threshold: {threshold_value:.4f} {reading.unit})"
        )
        return Alert(
            severity=severity,
            parameter=reading.parameter,
            reading=reading,
            message=message,
            threshold_value=threshold_value,
        )

    def _dispatch(self, alert: Alert) -> None:
        for handler in self._handlers:
            try:
                handler.notify(alert)
            except Exception as exc:  # noqa: BLE001
                logger.error(
                    "Handler %s failed to process alert %s: %s",
                    handler,
                    alert.alert_id,
                    exc,
                )
